[project]
name = "repl-nix-new-repl-1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.57.4",
    "pandas>=2.2.3",
    "streamlit>=1.41.1",
]
